apiVersion: apps/v1
kind: Deployment
metadata:
  name: approval-engine-service
  labels:
    app: approval-engine-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: approval-engine-service
  template:
    metadata:
      labels:
        app: approval-engine-service
    spec:
      containers:
        - name: approval-engine-service
          image: approval-engine-service:v1
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: approval-engine-service
spec:
  selector:
    app: approval-engine-service
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer
